// Third-party app connections shown on the Integration Hub page. Distinct
// from server/schema.ts's `integrations` table (webhook receiver configs) —
// this is illustrative marketplace-style data, not wired to a real backend.
export const integrations = [
  {
    name: "Stripe",
    category: "Payments",
    status: "connected",
    sync: "2m ago",
    events: "184K/mo",
    icon: "S",
  },
  {
    name: "Salesforce",
    category: "CRM",
    status: "syncing",
    sync: "syncing…",
    events: "62K/mo",
    icon: "SF",
  },
  {
    name: "AWS",
    category: "Infrastructure",
    status: "connected",
    sync: "just now",
    events: "1.2M/mo",
    icon: "AW",
  },
  {
    name: "Slack",
    category: "Communication",
    status: "connected",
    sync: "1m ago",
    events: "38K/mo",
    icon: "SL",
  },
  {
    name: "HubSpot",
    category: "Marketing",
    status: "error",
    sync: "18m ago",
    events: "24K/mo",
    icon: "HS",
  },
  {
    name: "Zendesk",
    category: "Support",
    status: "connected",
    sync: "4m ago",
    events: "51K/mo",
    icon: "ZD",
  },
  {
    name: "Snowflake",
    category: "Data Warehouse",
    status: "connected",
    sync: "12m ago",
    events: "88M/mo",
    icon: "SN",
  },
  {
    name: "GitHub",
    category: "DevOps",
    status: "connected",
    sync: "3m ago",
    events: "9.2K/mo",
    icon: "GH",
  },
  {
    name: "Notion",
    category: "Docs",
    status: "syncing",
    sync: "syncing…",
    events: "12K/mo",
    icon: "NO",
  },
  {
    name: "Segment",
    category: "Analytics",
    status: "connected",
    sync: "6m ago",
    events: "440K/mo",
    icon: "SG",
  },
  {
    name: "Twilio",
    category: "Comms",
    status: "connected",
    sync: "1m ago",
    events: "72K/mo",
    icon: "TW",
  },
  {
    name: "PagerDuty",
    category: "Incidents",
    status: "error",
    sync: "1h ago",
    events: "1.1K/mo",
    icon: "PD",
  },
] as const;

export type IntegrationStatus = "connected" | "syncing" | "error";
